=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

The version of the OpenAPI document: 0.26.0
Contact: contact@skycoin.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SkyApi::BlockVerboseSchema
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BlockVerboseSchema' do
  before do
    # run before each test
    @instance = SkyApi::BlockVerboseSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlockVerboseSchema' do
    it 'should create an instance of BlockVerboseSchema' do
      expect(@instance).to be_instance_of(SkyApi::BlockVerboseSchema)
    end
  end
  describe 'test attribute "header"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "body"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
