=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

The version of the OpenAPI document: 0.26.0
Contact: contact@skycoin.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SkyApi::TransactionEncodedS
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TransactionEncodedS' do
  before do
    # run before each test
    @instance = SkyApi::TransactionEncodedS.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionEncodedS' do
    it 'should create an instance of TransactionEncodedS' do
      expect(@instance).to be_instance_of(SkyApi::TransactionEncodedS)
    end
  end
  describe 'test attribute "time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "encoded_transaction"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
