lang: ruby

env:
  global:
    - CGO_ENABLED: 1

install:
  # Install gox
  - go env
  - go get github.com/gz-c/gox
  - go get -t ./...

script: 
    - ./travis/skyapi.sh
    - make build

rvm: 2.5

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
