lang: ruby
rvm: 2.5
env:
  global:
    - CGO_ENABLED: 1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
install:
  - eval "$(gimme 1.10)" 
  # Install gox
  - go env
  - go get github.com/gz-c/gox

before_script:
  - make -C gopath/src/github.com/skycoin/libskycoin dep
script: 
  - ./.travis/skyapi.sh
  - make build

before_deploy:
  - make package

deploy:
  provider: releases
  api_key: "1b6483754e66bd7cc6233db548ce9695cc8ecdc4"
  file:
    - ./lib/skyapi/skyapi-${TRAVIS_TAG}.gem
    - ./lib/skycoin/skycoin-${TRAVIS_TAG}.gem
  skip_cleanup: true
  on:
    tags: true
    repo: simelo/libjava-skycoin

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
