=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

The version of the OpenAPI document: 0.27.0
Contact: contact@skycoin.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.3

=end

# Common files
require 'sky_api/api_client'
require 'sky_api/api_error'
require 'sky_api/version'
require 'sky_api/configuration'

# Models
require 'sky_api/models/address'
require 'sky_api/models/api_v1_pending_txs_transaction'
require 'sky_api/models/api_v1_pending_txs_transaction_outputs'
require 'sky_api/models/block_schema'
require 'sky_api/models/block_schema_body'
require 'sky_api/models/block_verbose_schema'
require 'sky_api/models/block_verbose_schema_body'
require 'sky_api/models/block_verbose_schema_header'
require 'sky_api/models/inline_response200'
require 'sky_api/models/inline_response2001'
require 'sky_api/models/inline_response20010'
require 'sky_api/models/inline_response2002'
require 'sky_api/models/inline_response2003'
require 'sky_api/models/inline_response2004'
require 'sky_api/models/inline_response2005'
require 'sky_api/models/inline_response2006'
require 'sky_api/models/inline_response2007'
require 'sky_api/models/inline_response2008'
require 'sky_api/models/inline_response2008_data'
require 'sky_api/models/inline_response2009'
require 'sky_api/models/inline_response_default'
require 'sky_api/models/network_connection_schema'
require 'sky_api/models/network_connection_schema_unconfirmed_verify_transaction'
require 'sky_api/models/transaction'
require 'sky_api/models/transaction_encoded'
require 'sky_api/models/transaction_encoded_s'
require 'sky_api/models/transaction_status'
require 'sky_api/models/transaction_txn'
require 'sky_api/models/transaction_v2_params_address'
require 'sky_api/models/transaction_v2_params_address_hours_selection'
require 'sky_api/models/transaction_v2_params_unspent'
require 'sky_api/models/transaction_v2_params_unspent_hours_selection'
require 'sky_api/models/transaction_v2_params_unspent_to'
require 'sky_api/models/transaction_verbose'
require 'sky_api/models/transaction_verbose_txn'
require 'sky_api/models/transaction_verbose_txn_inputs'
require 'sky_api/models/transaction_verify_request'
require 'sky_api/models/wallet_transaction_request'
require 'sky_api/models/wallet_transaction_request_hours_selection'
require 'sky_api/models/wallet_transaction_request_wallet'
require 'sky_api/models/wallet_transaction_sign_request'

# APIs
require 'sky_api/api/default_api'

module SkyApi
  class << self
    # Customize default settings for the SDK using block.
    #   SkyApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
